sssdutils: adding with-mkhomedir common configuration
SSSD/sssd-test-framework pull request #125
Opened 2024-09-23 16:42 UTC by danlavu

* fixed some minor docstrings typos

2024-09-24 02:32 UTC, danlavu commented
Test >> https://github.com/SSSD/sssd/pull/7617

2024-09-24 09:59 UTC, pbrezina requested changes
Hi Dan, could you please split the doc changes to another commit?

It is a good practice to keep commits small so it is easy to revert the patch if needed. If you revert the patch now, you also revert the doc changes.

Otherwise ack.

2024-09-24 19:12 UTC, danlavu commented
@pbrezina Done, added one thing to the function, parameterized the homedir path and it defaults to '/home'

2024-09-25 10:00 UTC, pbrezina approved these changes

2024-09-25 10:01 UTC, merged