genconf command added
SSSD/sssd-test-framework pull request #4
Opened 2023-05-02 11:08 UTC by patriki01

2023-05-09 09:29 UTC, pbrezina requested changes

2023-05-09 09:29 UTC, pbrezina commented on sssd_test_framework/utils/sssd.py
> +    def genconf_section(self, section: str) -> SSHProcessResult:
This can be merged into genconf method.

2023-05-09 13:18 UTC, patriki01 commented on sssd_test_framework/utils/sssd.py
> +    def genconf_section(self, section: str) -> SSHProcessResult:
Done

2023-05-10 12:17 UTC, pbrezina requested changes
Please change the commit message to "sssd: add genconf method"

2023-05-10 12:17 UTC, pbrezina commented on sssd_test_framework/utils/sssd.py
> +        :param section: Section that will be refreshed. Defaults to None.
\``None``

2023-05-10 12:17 UTC, pbrezina commented on sssd_test_framework/utils/sssd.py
> +        Exec ``sssd --genconf`` or ``sssd --genconf-section=section`` while section is not None.
if \``section`` is not \``None``.

2023-05-17 11:39 UTC, pbrezina requested changes

2023-05-18 06:24 UTC, patriki01 commented on sssd_test_framework/utils/sssd.py
> +        return cmd
I thought that the way I did it it was more clear. But I see now it is not. FIXED.

2023-05-23 10:25 UTC, pbrezina approved these changes

2023-05-23 10:25 UTC, merged