roles: adding optional email parameter to ad user add
SSSD/sssd-test-framework pull request #88
Opened 2024-02-21 04:22 UTC by danlavu

2024-02-21 05:50 UTC, danlavu commented
We have a test case worth automating https://github.com/SSSD/sssd/pull/7174 , using the email instead of the userid to login. To adequately test this, we need to be able to change the email value of the user created in AD.

2024-02-21 06:57 UTC, danlavu commented
Test case https://github.com/SSSD/sssd/pull/7206

2024-02-21 11:11 UTC, pbrezina commented
LGTM, can you please add it also to Samba? There's `--mail-address` parameter. It would also be nice if we are able to change it in `modify()`.

2024-02-29 10:34 UTC, pbrezina requested changes

2024-02-29 10:34 UTC, pbrezina commented on sssd_test_framework/roles/ad.py
> +        :param email: Email, defaults to None
`defaults to None (= user@domain)`, same in samba

2024-03-06 16:13 UTC, merged