roles: ad, adding ADSites class to create new sites objects
SSSD/sssd-test-framework pull request #96
Opened 2024-03-27 03:57 UTC by danlavu

2024-03-27 04:01 UTC, danlavu commented
GPO tests need to be able to create a new site. Also the restore, cn=sites,cn=configuration is in the config part of the directory and needs to be explicitly set to be searched.

2024-04-03 11:38 UTC, pbrezina submitted a review, later dismissed

2024-04-03 19:31 UTC, spoore1 requested changes
Just one very minor nitpick for a docstring.

2024-04-03 19:31 UTC, spoore1 commented on sssd_test_framework/roles/ad.py
> +        .. code-blocK:: python
Change to lowercase K in code-blocK?

2024-04-04 13:15 UTC, spoore1 approved these changes
LGTM

2024-04-05 12:40 UTC, merged